import React, { useState, useEffect } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { Box, Typography, IconButton } from "@mui/material";
import ArrowBackIcon from "@mui/icons-material/ArrowBack";

function ResultPage() {
  const location = useLocation();
  const navigate = useNavigate();
  const [domain, setDomain] = useState("");
  const [language, setLanguage] = useState("");
  const [inputText, setInputText] = useState("");
  const [selectedSection, setSelectedSection] = useState("");

  // location.state is in json format
  useEffect(() => {
    if (location.state) {
      const { domain, language, inputText } = location.state;
      setDomain(domain || "");
      setLanguage(language || "");
      setInputText(inputText || "");
    }
  }, [location.state]);

  const handleClick = (section) => {
    setSelectedSection(section);
  };

  const handleBack = () => {
    navigate("/");
  };

  const renderContent = () => {
    switch (selectedSection) {
      case "Result":
        return (
          <div>
            <Typography variant="h5">Document Generated</Typography>
            <Typography variant="body1">
              <h3>The following content is to be generated by llm </h3>

              <h4>Heading 1: Title of Heading 1</h4>
              <h5> Subheading 1 for Heading 1 </h5>

              <p>
                delectus aut autem quis ut nam facilis et officia qui fugiat
                veniam minus et porro tempora laboriosam mollitia et enim quasi
                adipisci quia provident illum qui ullam ratione quibusdam
                voluptatem quia omnis illo expedita consequatur quia in quo
                adipisci enim quam ut ab molestiae perspiciatis ipsa illo est
                ratione doloremque quia maiores aut vero rerum temporibus dolor
                ipsa repellendus fugit nisi
              </p>

              <h5> Subheading 2 for Heading 1 </h5>

              <p>
                delectus aut autem quis ut nam facilis et officia qui fugiat
                veniam minus et porro tempora laboriosam mollitia et enim quasi
                adipisci quia provident illum qui ullam ratione quibusdam
                voluptatem quia omnis illo expedita consequatur quia in quo
                adipisci enim quam ut ab molestiae perspiciatis ipsa illo est
                ratione doloremque quia maiores aut vero rerum temporibus dolor
                ipsa repellendus fugit nisi
              </p>

              {/* New heading */}
              <h4>Heading 2: Title of Heading 2</h4>
              <h5> Subheading 2 for Heading 2 </h5>
              <p>
                delectus aut autem quis ut nam facilis et officia qui fugiat
                veniam minus et porro tempora laboriosam mollitia et enim quasi
                adipisci quia provident illum qui ullam ratione quibusdam
                voluptatem quia omnis illo expedita consequatur quia in quo
                adipisci enim quam ut ab molestiae perspiciatis ipsa illo est
                ratione doloremque quia maiores aut vero rerum temporibus dolor
                ipsa repellendus fugit nisi
              </p>

              <h4>Heading 3: Title of Heading 3</h4>

              <p>
                delectus aut autem quis ut nam facilis et officia qui fugiat
                veniam minus et porro tempora laboriosam mollitia et enim quasi
                adipisci quia provident illum qui ullam ratione quibusdam
                voluptatem quia omnis illo expedita consequatur quia in quo
                adipisci enim quam ut ab molestiae perspiciatis ipsa illo est
                ratione doloremque quia maiores aut vero rerum temporibus dolor
                ipsa repellendus fugit nisi
              </p>

              <h4>Heading 3: Title of Heading 3</h4>

              <p>
                delectus aut autem quis ut nam facilis et officia qui fugiat
                veniam minus et porro tempora laboriosam mollitia et enim quasi
                adipisci quia provident illum qui ullam ratione quibusdam
                voluptatem quia omnis illo expedita consequatur quia in quo
                adipisci enim quam ut ab molestiae perspiciatis ipsa illo est
                ratione doloremque quia maiores aut vero rerum temporibus dolor
                ipsa repellendus fugit nisi
              </p>
              <h4>Heading 3: Title of Heading 3</h4>

              <p>
                delectus aut autem quis ut nam facilis et officia qui fugiat
                veniam minus et porro tempora laboriosam mollitia et enim quasi
                adipisci quia provident illum qui ullam ratione quibusdam
                voluptatem quia omnis illo expedita consequatur quia in quo
                adipisci enim quam ut ab molestiae perspiciatis ipsa illo est
                ratione doloremque quia maiores aut vero rerum temporibus dolor
                ipsa repellendus fugit nisi
              </p>
            </Typography>
          </div>
        );
      case "Domain":
        return (
          <div>
            <Typography variant="h5">{domain}</Typography>
            <Typography variant="body1">
              Detailed information about {domain}.
            </Typography>
          </div>
        );
      case "Language":
        return (
          <div>
            <Typography variant="h5">{language}</Typography>
            <Typography variant="body1">
              Detailed information about the {language} language.
            </Typography>
          </div>
        );
      case "Text":
        return (
          <div>
            <Typography variant="h5">Input Text</Typography>
            <Typography variant="body1">{inputText}</Typography>
          </div>
        );
      default:
        return (
          <Typography variant="body1">
            Select a section to preview details
          </Typography>
        );
    }
  };

  return (
    <Box
      display="flex"
      flexDirection="row"
      minHeight="100vh"
      padding={2}
      bgcolor="background.default"
    >
      <Box
        flex="1 1 50%"
        padding={2}
        borderRight="5px solid"
        borderColor="divider"
      >
        {/* Go back button */}
        <IconButton onClick={handleBack} style={{ marginRight: 15 }}>
          <ArrowBackIcon />
          Back
        </IconButton>
        {/* Generate Document */}
        <IconButton
          onClick={() => handleClick("Result")}
          style={{ cursor: "pointer", marginLeft: 16 }}
          onMouseEnter={(e) => {
            e.currentTarget.style.backgroundColor = "#f0f0f0"; // Highlight color
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.backgroundColor = "transparent";
          }}
        >
          <Typography variant="h5"> Click here to Generate Document</Typography>
        </IconButton>

        <Typography variant="h5" style={{ marginBottom: 15 }}>
          Outline of document
        </Typography>

        {/* <Typography
          variant="body1"
          style={{ marginLeft: 16, cursor: "pointer" }}
          onClick={() => handleClick("Result")}
          onMouseEnter={(e) => (e.target.style.textDecoration = "underline")}
          onMouseLeave={(e) => (e.target.style.textDecoration = "none")}
        >
          Subheading 1: Analysis
        </Typography>
        <Typography
          variant="body1"
          style={{ marginLeft: 16, cursor: "pointer" }}
          onClick={() => handleClick("Result")}
          onMouseEnter={(e) => (e.target.style.textDecoration = "underline")}
          onMouseLeave={(e) => (e.target.style.textDecoration = "none")}
        >
          Subheading 2: Insights
        </Typography> */}
        <Typography
          variant="h6"
          style={{ marginBottom: 8, marginTop: 16 /*cursor: "pointer" */ }}
          // onClick={() => handleClick("Domain")}
          onMouseEnter={(e) => {
            e.currentTarget.style.backgroundColor = "#f0f0f0"; // Highlight color
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.backgroundColor = "transparent";
          }}
        >
          Heading 1
        </Typography>
        <Typography
          variant="body1"
          style={{ marginLeft: 16, cursor: "pointer" }}
          onClick={() => handleClick("Domain")}
          onMouseEnter={(e) => (e.target.style.textDecoration = "underline")}
          onMouseLeave={(e) => (e.target.style.textDecoration = "none")}
        >
          Subheading 1: Details
        </Typography>
        <Typography
          variant="body1"
          style={{ marginLeft: 16, cursor: "pointer" }}
          onClick={() => handleClick("Domain")}
          onMouseEnter={(e) => (e.target.style.textDecoration = "underline")}
          onMouseLeave={(e) => (e.target.style.textDecoration = "none")}
        >
          Subheading 2: Details2
        </Typography>
        <Typography
          variant="body1"
          style={{ marginLeft: 16, cursor: "pointer" }}
          onClick={() => handleClick("Domain")}
          onMouseEnter={(e) => (e.target.style.textDecoration = "underline")}
          onMouseLeave={(e) => (e.target.style.textDecoration = "none")}
        >
          Subheading 3: Details3
        </Typography>
        <Typography
          variant="body1"
          style={{ marginLeft: 16, cursor: "pointer" }}
          onClick={() => handleClick("Domain")}
          onMouseEnter={(e) => (e.target.style.textDecoration = "underline")}
          onMouseLeave={(e) => (e.target.style.textDecoration = "none")}
        >
          Subheading 4: More insights4
        </Typography>
        <Typography
          variant="h6"
          style={{ marginBottom: 8, marginTop: 16 /*cursor: "pointer" */ }}
          // onClick={() => handleClick("Language")}
          onMouseEnter={(e) => {
            e.currentTarget.style.backgroundColor = "#f0f0f0"; // Highlight color
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.backgroundColor = "transparent";
          }}
        >
          Heading 2
        </Typography>
        <Typography
          variant="body1"
          style={{ marginLeft: 16, cursor: "pointer" }}
          onClick={() => handleClick("Language")}
          onMouseEnter={(e) => (e.target.style.textDecoration = "underline")}
          onMouseLeave={(e) => (e.target.style.textDecoration = "none")}
        >
          Subheading 1: Language details
        </Typography>
        <Typography
          variant="body1"
          style={{ marginLeft: 16, cursor: "pointer" }}
          onClick={() => handleClick("Domain")}
          onMouseEnter={(e) => (e.target.style.textDecoration = "underline")}
          onMouseLeave={(e) => (e.target.style.textDecoration = "none")}
        >
          Subheading 2: Details
        </Typography>
        <Typography
          variant="body1"
          style={{ marginLeft: 16, cursor: "pointer" }}
          onClick={() => handleClick("Domain")}
          onMouseEnter={(e) => (e.target.style.textDecoration = "underline")}
          onMouseLeave={(e) => (e.target.style.textDecoration = "none")}
        >
          Subheading 3: Details
        </Typography>
        <Typography
          variant="body1"
          style={{ marginLeft: 16, cursor: "pointer" }}
          onClick={() => handleClick("Language")}
          onMouseEnter={(e) => (e.target.style.textDecoration = "underline")}
          onMouseLeave={(e) => (e.target.style.textDecoration = "none")}
        >
          Subheading 4: Usage
        </Typography>
        <Typography
          variant="body1"
          style={{ marginLeft: 16, cursor: "pointer" }}
          onClick={() => handleClick("Domain")}
          onMouseEnter={(e) => (e.target.style.textDecoration = "underline")}
          onMouseLeave={(e) => (e.target.style.textDecoration = "none")}
        >
          Subheading 5: Details 5
        </Typography>
        <Typography
          variant="h6"
          style={{ marginBottom: 8, marginTop: 16 /*cursor: "pointer" */ }}
          // onClick={() => handleClick("Text")}
          onMouseEnter={(e) => {
            e.currentTarget.style.backgroundColor = "#f0f0f0"; // Highlight color
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.backgroundColor = "transparent";
          }}
        >
          Heading 3
        </Typography>
        <Typography
          variant="body1"
          style={{ marginLeft: 16, cursor: "pointer" }}
          onClick={() => handleClick("Text")}
          onMouseEnter={(e) => (e.target.style.textDecoration = "underline")}
          onMouseLeave={(e) => (e.target.style.textDecoration = "none")}
        >
          Subheading 1: Text analysis
        </Typography>
        <Typography
          variant="body1"
          style={{ marginLeft: 16, cursor: "pointer" }}
          onClick={() => handleClick("Text")}
          onMouseEnter={(e) => (e.target.style.textDecoration = "underline")}
          onMouseLeave={(e) => (e.target.style.textDecoration = "none")}
        >
          Subheading 2: Additional notes
        </Typography>
        <Typography
          variant="body1"
          style={{ marginLeft: 16, cursor: "pointer" }}
          onClick={() => handleClick("Domain")}
          onMouseEnter={(e) => (e.target.style.textDecoration = "underline")}
          onMouseLeave={(e) => (e.target.style.textDecoration = "none")}
        >
          Subheading 3: Details
        </Typography>
        <Typography
          variant="body1"
          style={{ marginLeft: 16, cursor: "pointer" }}
          onClick={() => handleClick("Domain")}
          onMouseEnter={(e) => (e.target.style.textDecoration = "underline")}
          onMouseLeave={(e) => (e.target.style.textDecoration = "none")}
        >
          Subheading 4: Details
        </Typography>
      </Box>
      <Box flex="1 1 50%" padding={2}>
        {renderContent()}
      </Box>
    </Box>
  );
}

export default ResultPage;
